### ISSUE TITLE
Request: Forestry support/ Producers

### ISSUE THREAD

**Issue by CurePindal** [portablejim/PowerConverters#27]
Hello!
Is it possible to add support for Forestry? It would be fantastic to be able to use Forestry with other power systems than IC/BC. (like Flaxbeards Steam Mod).
Forestry seems to use the MJ-system of BuildCraft but the MJ producers arent available without BC installed.

Thanks for considering!

**Comment by grydian** [comment]
Forestry no longer uses MJs.  MJs are no longer being used at all.  Even buildcraft has dropped them.

**Comment by Chocohead** [comment]
Guessing maybe this is for 1.6.4?

**Comment by CurePindal** [comment]
No. Just havent seen that Forestry now accepts RF, too.
Still theres no producers for Forestry, so the request for Forestry support is still on!

**Comment by grydian** [comment]
Since forestry runs on and uses RF the producers to use are the RF producers.  So why do you need something that is already there.  Are you wanting the recipe to use forestry items?  Because at this point it works with forestry.

**Comment by CurePindal** [comment]
@grydian, short answer: Install PC, install forestry and you will see theres no producers available to build. The producers are only craftable when the "core mod" of the energy system is installed too. So if you input steam you cant export RF to Forestry. 
Hence a Forestry integration is needed, so all valid producers are craftable when Forestry is present.
