### ISSUE TITLE
IC2 Consumers not working - Power Converters 3.2.0

### ISSUE THREAD

**Issue by chloeprince** [portablejim/PowerConverters#33]
In the latest version of Power Converters, all IC2 consumers are disabled. All others work, but anything consumer that attempts to use IC2 Power, it doesn't work.

industrialcraft-2-2.2.718-experimental.jar
Forge .1388

**Comment by portablejim** [comment]
Try giving it a redstone signal. If it makes it work, it is still a bug, but I know exactly what the bug is (I think)

**Comment by portablejim** [comment]
Should be fixed now. (At least I tested it and it worked). Complain here if it not.

**Comment by chloeprince** [comment]
I used PowerConverters-1.7.10_3.2.2-jenkins.69.jar from your Jenkins site, and it seems to be working again. Great job! Than you.

**Comment by chloeprince** [comment]
ummm.... wait. You may want to double check the conversion rates from EU to RF.  They have changed. Basically, I am getting so much RF now from EU, that if I use Mekanism cable and loop back from my RF producer to my EU consumer, I can make an infinite power source because more RF is being made from the EU that it took to make it.
