### ISSUE TITLE
Build 75: GT Producers treated as GT Consumers by Energy Bridge

### ISSUE THREAD

**Issue by walkerjonny** [portablejim/PowerConverters#47]
Hi, 
With the newest build 75 the GregTech Producers act now as GregTech Consumers and not as Producers as they are supposed to do.
The Energy Bridge treats them as input and not as output as it should do.
The result is that GregTech machines on the output side get no power anymore.
Can you have a look at this, please?

**Comment by walkerjonny** [comment]
I did a deeper testing now.
That issue occurs with the whole 3.3.0 branch beginning from build 72 up to 75.
I did a minimal test with only IC2, GregTech, Power Converters, Optifine and NEI plus required code chicken libs.

**Comment by ultrasn0w** [comment]
I already fixed that, see https://github.com/portablejim/PowerConverters/pull/45
Only needs to be merged now.

**Comment by walkerjonny** [comment]
I have seen it and also your fork. 
Well, over the past weeks I have gained the impression that portablejim has somewhat lost his interest to maintain this really cool and helpful mod.
He did a pretty good job there so his version of the power converters is the best one out there in my opinion.
If you know how to compile your fork could you please post a link to your jar file to your forked power converters github page?
As I remember there should be no license issues because the original developer powercrystals allowed this in his license. 
Maybe you also want to post this link to his minecraftforum thread.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293983-powerconverters-originally-by-powercrystals

**Comment by ultrasn0w** [comment]
There you go: https://github.com/ultrasn0w/PowerConverters/releases/tag/Fix

Look up the commits to see what's changed if you're curious. (A very dirty remove of MFFS)

MC Forum thread post coming later.

**Comment by walkerjonny** [comment]
When did you remove MFFS?
As you created that fix a few days ago or today as you posted it on the github page?
I assume today as you tried to compile and publish the jar. 
I did set up gradle and JDK today just to compile your forked repository.
There was a download issue with the required resonant engine library that tricked me a bit until I managed to download the required files manually and to set up a local web server with a working download path that I added into the build.gradle. After that I was able to compile the jar successfully.
I can send you the required resonant engine files zipped per mail if you want.
And I can also send you my compiled jar, if you want.

**Comment by walkerjonny** [comment]
Uhm, now I see it.
There is a crash on loading with the MFFS files included. That seems to be the reason why you have removed it.

**Comment by ultrasn0w** [comment]
Exactly, but I wonder why gradle tried to download Resonant Engine in your setup since I removed it from build.gradle. (Assuming you took mine) 
Actually I made these changes a few days ago since I also needed a fixed version on my MC Server and the compile ran completely fine first try after I made these changes. 
Do you really need MFFS energy? If not just use my compiled jar, it seems to be working fine. 
I still hope for portablejim to continue his work,  he did a pretty good job.

**Comment by walkerjonny** [comment]
Yes, I took yours. Otherwise the GT Producers would not work. And they do - at least in the old limitation.
(That is only 1 A per tick even if the request is higher. You have to attach cables to each free side of the producer to increase the A output per tick.)
But it seems that I got somehow a repository without that gradle changes you did. Strange...
I have tried a newer resonant engine build - 394. With that one loading Minecraft succeeded. I'll do a test in game to see if everything is ok.

**Comment by walkerjonny** [comment]
Seems to work that way.
It looks like the old build 368 was too old then.
